name:                azupdate
version:             0.1.0.0
github:              "githubuser/azupdate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/azupdate#readme>

dependencies:
- amazonka
- amazonka-core
- hal
- lens
- text
- aeson
- aeson-casing
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  azupdate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -j4
    - -O2
    - -fwrite-ide-info
    - -hiedir=.hie
    - -threaded
    - -static
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - azupdate

tests:
  azupdate-test:
    main:                Spec.hs
    source-dirs:         
      - test
      - src
    ghc-options:
    - -j4
    - -O2
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - azupdate

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - NamedFieldPuns
  - ViewPatterns
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric